name: Build and Deploy

on:
  push:
    branches: [ main ]   # deploy when you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'   # LTS is fine

      - run: npm install
      - run: npm run build

      # Upload dist/ to Hostinger via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist
          # Adjust if your web root is different:
          server-dir: public_html
